#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}


# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=7

REPO=/Volumes/Data2/mytube-app
IPA="$REPO/dist/Mytube-release.ipa"
UDID=F87D1CA1-CE10-5EDC-B3B0-8784DC11BD3E
ALTSTORE_ID=com.rileytestut.AltStore
APP_ID=com.xtube.com

# apps lists the user apps on the phone, one "bundleid version" per line.
# `devicectl` prints a table with a header and a rule; the tail is the rows.
apps() {
  xcrun devicectl device info apps --device "$UDID" 2>/dev/null \
    | awk '/^-+ /{seen=1;next} seen && NF{print $2, $3}'
}

# wait_for BUNDLE_ID "what" polls until it shows up, or the human gives up.
# A poll rather than a question: "is it there yet" is a thing the Mac can
# answer, and a wizard that asks what it could check is one that believes a
# tired yes.
wait_for() {
  local id="$1" what="$2" n=0
  printf '  %s…%s waiting for %s' "$DIM" "$RESET" "$what"
  while (( n < 60 )); do
    if apps | grep -q "^$id "; then printf '\n'; printf '  %s✓%s %s is on the phone\n' "$GREEN" "$RESET" "$what"; return 0; fi
    printf '.'; sleep 5; n=$((n + 1))
  done
  printf '\n'; warn "$what has not appeared after five minutes"
  return 1
}

banner "AltStore on the iPhone"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "The build you are about to install"
say "AltStore re-signs whatever it is handed, so check it is the build you want"
say "before spending the seven days on it."
if [[ ! -f "$IPA" ]]; then
  warn "no IPA at $IPA"
  say "Build one first:  cd $REPO && ./tools/ios-ipa.sh"
  SKIPPED+=("build the IPA: ./tools/ios-ipa.sh")
else
  BUILT=$(unzip -p "$IPA" 'Payload/*.app/Info.plist' 2>/dev/null \
          | plutil -extract CFBundleShortVersionString raw - 2>/dev/null || echo "?")
  WANT=$(grep -m1 'versionName = ' "$REPO/composeApp/build.gradle.kts" | sed 's/.*"\(.*\)".*/\1/')
  note "IPA        $BUILT   ($(du -h "$IPA" | cut -f1), $(date -r "$IPA" '+%d %b %H:%M'))"
  note "repo says  $WANT"
  if [[ "$BUILT" != "$WANT" ]]; then
    warn "the IPA is older than the source"
    if confirm "Rebuild it now? (a few minutes)"; then
      ( cd "$REPO" && ./tools/ios-ipa.sh ) || warn "the build failed; carrying on with the old IPA"
    fi
  fi
fi
pause "Press Enter to continue"

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Cable, and Wi-Fi sync in Finder"
say "AltServer installs over the cable. Wi-Fi sync is what lets it refresh the"
say "app every week afterwards without one."
step "Plug the iPhone into this Mac."
step "Open Finder and click the iPhone in the sidebar, under Locations."
step "On the General tab, tick 'Show this iPhone when on Wi-Fi'."
step "Press Apply, bottom right."
note "Unlock the phone and tap Trust if it asks whether to trust this computer."
open -a Finder 2>/dev/null || true
pause "Press Enter once Apply has been pressed"
if xcrun devicectl list devices 2>/dev/null | grep -q "$UDID"; then
  printf '  %s✓%s the Mac can see the phone\n' "$GREEN" "$RESET"
else
  warn "the Mac cannot see the phone; check the cable and the Trust prompt"
fi
pause "Press Enter to continue"

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "Start AltServer"
say "AltServer has no window and no Dock icon. It is the diamond in the menu"
say "bar, at the top right of the screen, beside the clock."
if pgrep -qf 'AltServer'; then
  printf '  %s✓%s AltServer is already running\n' "$GREEN" "$RESET"
else
  open -a AltServer 2>/dev/null || warn "could not launch /Applications/AltServer.app"
  sleep 3
  if pgrep -qf 'AltServer'; then
    printf '  %s✓%s AltServer started\n' "$GREEN" "$RESET"
  else
    warn "AltServer did not start; open it from Applications by hand"
  fi
fi
step "Find the diamond icon in the menu bar. If macOS asks to allow it, allow it."
pause "Press Enter once you can see the diamond"

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "Install AltStore onto the phone"
say "This is the step that needs the Apple ID. Type the password into"
say "AltServer's own dialog."
warn "This wizard never asks for it and must never be told it."
step "Click the diamond in the menu bar."
step "Choose 'Install AltStore' and then \"Nguyen Luc's iPhone\"."
step "Enter the household Apple ID and its password in the box AltServer opens."
note "With two-factor on, Apple sends a code to another device; AltServer asks for it."
note "A free Apple ID may hold three sideloaded apps at a time. Mytube is one."
pause "Press Enter once AltServer says it has finished"
wait_for "$ALTSTORE_ID" "AltStore" || SKIPPED+=("AltStore did not install; try the diamond → Install AltStore again")

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "Trust the certificate on the phone"
say "iOS will not open an app signed by an Apple ID it has not been told to"
say "trust. Until this is done AltStore bounces back to the home screen."
step "On the phone: Settings → General → VPN & Device Management."
step "Tap the entry under DEVELOPER APP that carries the household Apple ID."
step "Tap Trust, then Trust again in the sheet."
note "If there is no such entry, AltStore is not installed yet — go back a stage."
pause "Press Enter once it says Verified"
step "Open AltStore on the phone. It should reach its own screen and stay there."
pause "Press Enter once AltStore opens"

# ── 6 ─────────────────────────────────────────────────────────────────────
stage "Hand the IPA to AltStore"
say "The phone needs the file. AirDrop is the short way; a link on the house"
say "wifi is the way that works when AirDrop will not."
if [[ -f "$IPA" ]]; then
  if confirm "Reveal the IPA in Finder so you can AirDrop it?"; then
    open -R "$IPA"
    step "Right-click the file → Share → AirDrop → the iPhone."
    step "On the phone, accept it. It lands in Files, under Downloads."
  fi
  if confirm "Or serve it over the house wifi instead?"; then
    LAN=$(ipconfig getifaddr en0 2>/dev/null || ipconfig getifaddr en1 2>/dev/null)
    ( cd "$(dirname "$IPA")"; python3 -m http.server 8099 >/dev/null 2>&1 & echo $! > /tmp/altstore-serve.pid )
    say "In Safari on the phone, open:"
    printf '\n      %s%shttp://%s:8099/%s%s\n\n' "$BOLD" "$GREEN" "$LAN" "$(basename "$IPA")" "$RESET"
    step "Safari will download it. Open Files → Downloads to find it."
    note "The little server stops when this wizard finishes."
  fi
fi
step "In AltStore: My Apps → the + at the top left → pick Mytube-release.ipa."
note "It asks for the Apple ID password again here, and again that is AltStore's own box."
pause "Press Enter once AltStore shows Mytube under My Apps"
if [[ -f /tmp/altstore-serve.pid ]]; then
  kill "$(cat /tmp/altstore-serve.pid)" 2>/dev/null || true
  rm -f /tmp/altstore-serve.pid
fi
if apps | grep -q "^$APP_ID "; then
  printf '  %s✓%s %s\n' "$GREEN" "$RESET" "$(apps | grep "^$APP_ID ")"
else
  warn "the phone does not list $APP_ID"
fi

# ── 7 ─────────────────────────────────────────────────────────────────────
stage "Keep it alive without doing this again"
say "A free Apple ID's signature lasts seven days. AltStore renews it by itself"
say "while AltServer is running and both are on the house wifi — which is why"
say "stage 2 turned Wi-Fi sync on."
if osascript -e 'tell application "System Events" to get the name of every login item' 2>/dev/null | grep -q AltServer; then
  printf '  %s✓%s AltServer already starts with this Mac\n' "$GREEN" "$RESET"
elif confirm "Start AltServer automatically when this Mac logs in?"; then
  if osascript -e 'tell application "System Events" to make login item at end with properties {path:"/Applications/AltServer.app", hidden:true}' >/dev/null 2>&1; then
    printf '  %s✓%s added to Login Items\n' "$GREEN" "$RESET"
  else
    SKIPPED+=("add AltServer to System Settings → General → Login Items")
  fi
fi
note "To renew by hand: open AltStore → My Apps → Refresh All."
note "If it ever expires, the app opens and closes at once. That is the signature,"
note "not the app."
pause "Press Enter to finish"

finish
